apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: circleguard-dr
  labels:
    app: gateway-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: stixk/circleguard-gateway-service:dev-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: gateway-service-config
        - secretRef:
            name: circleguard-secrets
        resources:
          requests:
            memory: "192Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
