apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: circleguard-dr
  labels:
    app: file-service
    environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        environment: dev
    spec:
      containers:
      - name: file-service
        image: stixk/circleguard-file-service:dev-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: file-service-config
        - secretRef:
            name: circleguard-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
