apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: circleguard-dr
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: promotion-service